CREATING BACKUP FOR USER TABLE
CREATE TABLE `billbackup` (
`BILL_ID` int(11) ,
`BILL_DATE` DATE ,
`TOTAL_AMOUNT` int(11)
)






DELIMITER $$
CREATE PROCEDURE c()
BEGIN
DECLARE done int(11);
DECLARE BILL_ID VARCHAR(11);
DECLARE BILL_DATE DATE;
DECLARE TOTAL_AMOUNT int(11);

DECLARE BILL_STATUS int(11);
DECLARE TOTAL_AMOUNT int(11);
DECLARE DISCOUNT_AMOUNT int(11);
DECLARE Late_fee int(11);
DECLARE Late CHAR;

DECLARE cur CURSOR FOR SELECT * FROM BILLING_DETAILS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
OPEN cur;
label: LOOP
FETCH cur INTO BILL_ID,BILL_DATE,BILL_STATUS,DISCOUNT_AMOUNT,TOTAL_AMOUNT,Late_fee,BOOKING_ID,Late;
INSERT INTO billbackup VALUES(BILL_ID,BILL_DATE,TOTAL_AMOUNT);
IF done = 1 THEN LEAVE label;
END IF;
END LOOP;
CLOSE cur;
END;$$
DELIMITER ;

-- BILL_ID CHAR(6) NOT NULL,
--   BILL_DATE DATE NOT NULL,
--   BILL_STATUS CHAR(1) NOT NULL,
--   DISCOUNT_AMOUNT NUMERIC(10,2) NOT NULL,
--   TOTAL_AMOUNT NUMERIC(10,2) NOT NULL,
--   Late_fee NUMERIC(10,2) NOT NULL,
--   BOOKING_ID CHAR(5) NOT NULL,
--   Late CHAR NOT NULL,